name: SuperiorPrison
version: 1.0
api-version: 1.13
main: com.bgsoftware.superiorprison.SuperiorPrisonPlugin
description: Highly advanced prison core plugin
website: http://wildseries.xyz/
authors: [Ome_R, WildSeries]
depend: [Vault]

commands:
  ranks:
    description: List of ranks
    aliases: rank
  rankup:
    description: Upgrade your rank
    aliases: rankupgrade
  mines:
    description: List of mines
    aliases: mines